export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$PATH

#Zsh Autosuggestions
source ~/.config/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

#Zsh Syntax Highlighting - Catppuccin Theme
source ~/.config/zsh/plugins/catppuccin_macchiato-zsh-syntax-highlighting.zsh
source ~/.config/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

#Fuzzy Finder - Catpuccin Theme
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh
export FZF_DEFAULT_OPTS=" \
--color=bg+:#363a4f,bg:#24273a,spinner:#f4dbd6,hl:#ed8796 \
--color=fg:#cad3f5,header:#ed8796,info:#c6a0f6,pointer:#f4dbd6 \
--color=marker:#f4dbd6,fg+:#cad3f5,prompt:#c6a0f6,hl+:#ed8796"
export FZF_CTRL_R_OPTS="--reverse"
export FZF_TMUX_OPTS="-p"

#Bat - Catpuccin Theme
export BAT_THEME="Catppuccin-macchiato"

#Smart Tmux Session Manager
export PATH=$HOME/.config/tmux/plugins/t-smart-tmux-session-manager/bin:$PATH

#Aliases
source ~/.config/zsh/aliases

eval "$(zoxide init zsh)"
eval "$(starship init zsh)"
